apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  ingressClassName: nginx
  rules:
    - host: dtg.dev
      http:
        paths:
          - pathType: Prefix
            path: '/?(.*)'
            backend:
              service:
                name: apigateway-srv
                port:
                  number: 3000
  tls:
    - hosts:
        - dtg.dev
      secretName: dtg-cert-tls
