apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: brhamill/apigateway
          env:
            - name: AUTH_BASE_URI
              value: 'http://auth-srv:3000/v1'
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-srv
spec:
  selector:
    app: apigateway
  ports:
    - name: apigateway
      protocol: TCP
      port: 3000
      targetPort: 3000
